// src/lib/examContent.js
// CREATE this file at: src/lib/examContent.js
// Holds real content for every exam's 10 tabs. Keyed by exam "name" (must match Supabase exams.name exactly).

export const examContent = {

  UPSC: {
    full_name: "Union Public Service Commission — Civil Services Examination",
    official_url: "https://upsc.gov.in",
    category: "Civil Services",
    about: "UPSC CSE is India's most prestigious civil services exam, conducted annually to recruit officers for IAS, IPS, IFS, and 20+ other Group A & B central services. It is a 3-stage process: Prelims, Mains, and Interview, run by the Union Public Service Commission.",
    opportunities: "Selected candidates join as IAS (Administrative), IPS (Police), IFS (Foreign Service), IRS (Revenue), and other Group A officers — among the most powerful and respected government positions in India, with postings across districts, states, and embassies.",
    timeline: "Notification: February. Prelims: May/June. Mains: September. Interview: Feb-Apr (following year). Final result: ~12-15 months after notification.",
    eligibility: "Indian citizen, graduate in any discipline. Age 21-32 (General), with relaxation for OBC/SC/ST/PwD. Attempts: 6 (General), 9 (OBC), unlimited till age limit (SC/ST).",
    exam_pattern: "Prelims: GS Paper I (200 marks, 100 Qs) + CSAT Paper II (200 marks, qualifying). Mains: 9 descriptive papers (1750 marks). Interview: 275 marks. Total: 2025 marks.",
    cutoffs: "Prelims cutoff (General) typically 90-110/200. Final cutoff for IAS around 950-1000/2025 — varies by year.",
    application: "Apply online at upsc.gov.in via 'Online Application' link. Fee: ₹100 (General/OBC), free for Female/SC/ST/PwD.",
    after_exam: "Successful candidates undergo training at LBSNAA (Mussoorie) before joining their respective services and cadres.",
    faqs: "Q: Can engineers apply? A: Yes, any graduate is eligible. Q: Is the interview compulsory? A: Yes, for all qualifying candidates. Q: How long is the full process? A: Roughly 12-15 months from notification to final result.",
    disclaimer: "This information is for general guidance. Always verify exact dates, fees, and eligibility on the official UPSC website before applying.",
  },

  BPSC: {
    full_name: "Bihar Public Service Commission — Combined Competitive Examination",
    official_url: "https://bpsc.bihar.gov.in",
    category: "Civil Services",
    about: "BPSC CCE recruits candidates for Deputy Collector, DSP, and other Group A/B state government posts in Bihar. It follows a 3-stage process similar to UPSC: Prelims, Mains, and Interview.",
    opportunities: "Deputy Collector, Deputy SP, District Commandant (Home Guard), Supply Inspector, Block Panchayati Raj Officer, and various other Bihar state administrative posts.",
    timeline: "Notification and exam dates vary by year — BPSC typically runs multiple combined exams (e.g. 71st, 72nd CCE) with overlapping cycles. Check the official site for the current advertisement.",
    eligibility: "Bihar domicile required for most posts. Graduation from a recognized university. Age 20-37 (General), with relaxation for reserved categories.",
    exam_pattern: "Prelims: General Studies, 150 Qs, 150 marks, 2 hours. Mains: General Hindi (qualifying) + GS Paper I & II + Optional subject. Interview: 120 marks.",
    cutoffs: "Varies significantly by exam cycle and category — check official BPSC result PDFs for the most recent cutoffs.",
    application: "Apply via bpsconline.bihar.gov.in. Fee: ₹600 (General/OBC), ₹150 (SC/ST/PwD/Female).",
    after_exam: "Selected candidates undergo departmental training before being posted to their respective Bihar government roles.",
    faqs: "Q: Is Bihar domicile mandatory? A: Yes for most posts — check each advertisement. Q: Is Hindi compulsory? A: Yes, General Hindi is compulsory (qualifying) in Mains.",
    disclaimer: "BPSC frequently updates notifications and has multiple exam cycles running concurrently — always cross-check with bpsc.bihar.gov.in.",
  },

  UPPSC: {
    full_name: "Uttar Pradesh Public Service Commission",
    official_url: "https://uppsc.up.nic.in",
    category: "Civil Services",
    about: "UPPSC conducts the Combined State/Upper Subordinate Services Examination (PCS) to recruit officers for UP state administrative, police, and other Group A/B services.",
    opportunities: "Deputy Collector (SDM), DSP, Block Development Officer, Treasury Officer, and other UP state government Group A & B posts.",
    timeline: "Notification usually in the first half of the year; Prelims, Mains, and Interview follow over several months.",
    eligibility: "Graduate from a recognized university. Age 21-40 (General), with relaxation for reserved categories. UP domicile not always mandatory — check specific notification.",
    exam_pattern: "Prelims: GS Paper I + CSAT (qualifying). Mains: multiple descriptive papers. Interview: personality test.",
    cutoffs: "Varies by year and post — refer to official UPPSC result notifications.",
    application: "Apply online via uppsc.up.nic.in during the notified application window.",
    after_exam: "Selected candidates undergo training before joining their UP state cadre posting.",
    faqs: "Q: Is UP domicile required? A: Not always — check each specific recruitment notification.",
    disclaimer: "Always verify current details on uppsc.up.nic.in as notifications and patterns are updated periodically.",
  },

  "SSC CGL": {
    full_name: "Staff Selection Commission — Combined Graduate Level Examination",
    official_url: "https://ssc.gov.in",
    category: "Government Exams",
    about: "SSC CGL recruits graduates for Group B and C posts in various central government ministries and departments, including Income Tax Inspector, Excise Inspector, and Assistant Audit Officer.",
    opportunities: "Income Tax/Central Excise Inspector, Assistant Section Officer, Sub-Inspector (CBI/NIA), Statistical Investigator, Auditor, and more.",
    timeline: "Notification: usually mid-year. Tier 1 (CBT): a few months later. Tier 2: following Tier 1. Final result: typically within a year.",
    eligibility: "Bachelor's degree in any discipline. Age limit varies by post (typically 18-32), with relaxation for reserved categories.",
    exam_pattern: "Tier 1: Computer-based test (200 marks, 60 min) — GI&R, GA, Quant, English. Tier 2: Paper-based with subject-specific sections depending on post applied for.",
    cutoffs: "Varies significantly by post and category — check official SSC cutoff PDFs each year.",
    application: "Apply at ssc.gov.in during the application window. Fee: ₹100 (General/OBC), free for SC/ST/PwD/Female.",
    after_exam: "Document verification followed by post-specific training and joining at the allotted department.",
    faqs: "Q: Can final-year students apply? A: Yes, with proof of degree by a specified date. Q: Negative marking? A: Yes, typically 0.25-0.50 per wrong answer.",
    disclaimer: "Exam pattern and posts are revised periodically by SSC — confirm with the latest official notification.",
  },

  "SSC CHSL": {
    full_name: "Staff Selection Commission — Combined Higher Secondary Level Examination",
    official_url: "https://ssc.gov.in",
    category: "Government Exams",
    about: "SSC CHSL recruits 10+2 pass candidates for posts like Lower Division Clerk (LDC), Data Entry Operator (DEO), and Postal Assistant in central government offices.",
    opportunities: "LDC/Junior Secretariat Assistant, Data Entry Operator, Postal Assistant/Sorting Assistant, Court Clerk.",
    timeline: "Notification mid-year; Tier 1 (CBT) a few months after; Tier 2 (descriptive + typing/skill test) follows.",
    eligibility: "10+2 (Senior Secondary) pass from a recognized board. Age 18-27, with relaxation for reserved categories.",
    exam_pattern: "Tier 1: CBT — English, GK, Quant, Reasoning (200 marks). Tier 2: Descriptive paper + typing/data entry skill test.",
    cutoffs: "Varies by post and category each year.",
    application: "Apply at ssc.gov.in. Fee: ₹100 (General/OBC), free for SC/ST/PwD/Female.",
    after_exam: "Document verification, typing test (where applicable), then posting to the allotted department.",
    faqs: "Q: Is typing test compulsory? A: Yes for DEO and some clerk posts.",
    disclaimer: "Always confirm latest pattern and posts via the official SSC notification before applying.",
  },

  "SSC JE": {
    full_name: "Staff Selection Commission — Junior Engineer Examination",
    official_url: "https://ssc.gov.in",
    category: "Government Exams",
    about: "SSC JE recruits Junior Engineers (Civil, Mechanical, Electrical) for various central government departments like CPWD, MES, and Railways.",
    opportunities: "Junior Engineer posts in CPWD, Border Roads Organisation, Military Engineer Services, and other central engineering departments.",
    timeline: "Notification usually mid-year; Paper 1 (CBT) a few months later, Paper 2 (descriptive) follows.",
    eligibility: "Diploma/Degree in relevant Engineering discipline (Civil/Mechanical/Electrical). Age limit varies by post (typically up to 32).",
    exam_pattern: "Paper 1: CBT — General Awareness, Reasoning, General Engineering (200 marks). Paper 2: Descriptive engineering paper (300 marks).",
    cutoffs: "Varies by discipline, post, and category each year.",
    application: "Apply at ssc.gov.in. Fee: ₹100 (General/OBC), free for SC/ST/PwD/Female.",
    after_exam: "Document verification followed by posting to the allotted engineering department.",
    faqs: "Q: Is a degree required or is diploma enough? A: Diploma is sufficient for most posts — check exact notification.",
    disclaimer: "Confirm current eligibility and pattern details on ssc.gov.in before applying.",
  },

  "RRB NTPC": {
    full_name: "Railway Recruitment Board — Non-Technical Popular Categories",
    official_url: "https://www.rrbcdg.gov.in",
    category: "Government Exams",
    about: "RRB NTPC recruits for non-technical posts across Indian Railways including Station Master, Goods Guard, and Clerk — one of the largest government recruitment drives in India.",
    opportunities: "Station Master, Commercial Apprentice, Goods Guard, Senior Clerk, Junior Accounts Assistant, and other railway administrative posts.",
    timeline: "Notification, CBT 1, CBT 2, and document verification stages are spread across several months to a year depending on the recruitment cycle.",
    eligibility: "Graduation or 12th pass depending on the post category. Age 18-33, with relaxation for reserved categories.",
    exam_pattern: "CBT 1 (qualifying): General Awareness, Math, Reasoning. CBT 2: similar with higher difficulty. Followed by typing test/document verification depending on post.",
    cutoffs: "Varies widely by post, region (zone), and category.",
    application: "Apply via the official RRB regional website during the notified window.",
    after_exam: "Medical exam, document verification, then posting to a railway zone.",
    faqs: "Q: Can I apply to multiple RRB zones? A: No, only one zone per registration.",
    disclaimer: "RRB conducts recruitment region-wise — check your applicable zonal RRB website for exact details.",
  },

  ISRO: {
    full_name: "Indian Space Research Organisation — Scientist/Engineer Recruitment",
    official_url: "https://www.isro.gov.in/Careers.html",
    category: "Government Exams",
    about: "ISRO recruits Scientist/Engineer 'SC' candidates (BE/BTech graduates) directly through a written test and interview — a sought-after opportunity to work on India's space missions.",
    opportunities: "Scientist/Engineer roles in propulsion, satellite systems, launch vehicle design, and space research across ISRO centres (VSSC, SAC, URSC, etc.).",
    timeline: "Notification released when vacancies open (not strictly annual). Written test followed by interview within a few months.",
    eligibility: "BE/BTech (or equivalent) in relevant engineering discipline with minimum 65% marks (or CGPA equivalent). Age limit: 35 years.",
    exam_pattern: "Written exam: objective-type, discipline-specific engineering questions (for most recruitments). Followed by personal interview.",
    cutoffs: "Highly competitive — varies by discipline and number of vacancies each cycle.",
    application: "Apply online at isro.gov.in/Careers.html when a recruitment notification is active.",
    after_exam: "Selected candidates join as Scientist/Engineer 'SC' at an ISRO centre with a structured pay scale and research opportunities.",
    faqs: "Q: Is ISRO recruitment annual? A: No, it depends on vacancy requirements — watch the careers page for notifications.",
    disclaimer: "ISRO recruitment cycles are irregular — bookmark the official careers page for real-time updates.",
  },

  DRDO: {
    full_name: "Defence Research and Development Organisation — Scientist Recruitment",
    official_url: "https://www.drdo.gov.in/career",
    category: "Government Exams",
    about: "DRDO recruits Scientists ('B' grade and above) for defence research roles across its 50+ labs working on missiles, aeronautics, electronics, and materials science.",
    opportunities: "Scientist 'B' and above positions across DRDO labs (DRDL, ADA, CVRDE, etc.) working on cutting-edge defence technology.",
    timeline: "Recruitment (via DRDO-CEPTAM or direct) happens periodically based on vacancy — check the careers page regularly.",
    eligibility: "BE/BTech or equivalent in relevant engineering/science discipline, often with minimum 60-65% marks. Age limit typically 28 years (with relaxations).",
    exam_pattern: "Tier 1: objective-type technical exam. Tier 2: descriptive technical exam. Followed by interview for senior roles.",
    cutoffs: "Highly competitive, discipline-specific — varies each cycle.",
    application: "Apply at drdo.gov.in/career or via DRDO-CEPTAM portal when notifications are active.",
    after_exam: "Selected candidates join as Scientist 'B' at an assigned DRDO laboratory.",
    faqs: "Q: Does GATE score help for DRDO? A: Some DRDO recruitments accept GATE scores directly for certain posts.",
    disclaimer: "DRDO recruitment varies by lab and cycle — always confirm via the official careers portal.",
  },

  BARC: {
    full_name: "Bhabha Atomic Research Centre — Scientific Officer Recruitment",
    official_url: "https://www.barc.gov.in/careers/",
    category: "Government Exams",
    about: "BARC recruits Scientific Officers through its OCES/DGFS programs for nuclear research roles — among the most prestigious scientific careers in India.",
    opportunities: "Scientific Officer roles across BARC's nuclear, physics, chemistry, and engineering divisions, contributing to India's nuclear energy and research programs.",
    timeline: "OCES recruitment typically follows an annual cycle tied to engineering/science graduation; DGFS is integrated with select IITs/NITs.",
    eligibility: "BE/BTech/MSc in relevant discipline with strong academic record. Age limit and GATE score requirements vary by scheme (OCES/DGFS).",
    exam_pattern: "Written test (often GATE-score-based for OCES) followed by interview at BARC Training School.",
    cutoffs: "Highly competitive — GATE percentile cutoffs vary by discipline and year.",
    application: "Apply via barc.gov.in/careers when OCES/DGFS notifications open (usually aligned with academic year).",
    after_exam: "Selected candidates undergo a one-year training course at BARC Training School before permanent posting.",
    faqs: "Q: Is GATE score mandatory? A: For OCES, a valid GATE score is typically required as part of eligibility.",
    disclaimer: "BARC's OCES/DGFS schemes have specific annual cycles — confirm exact dates on the official careers page.",
  },

  "BSSC JE": {
    full_name: "Bihar Staff Selection Commission — Junior Engineer Examination",
    official_url: "https://bssc.bihar.gov.in",
    category: "Government Exams",
    about: "BSSC JE recruits Junior Engineers (Civil, Mechanical, Electrical) for various Bihar state government departments and PSUs.",
    opportunities: "Junior Engineer posts in Bihar's Public Works Department, Rural Works Department, and other state engineering departments.",
    timeline: "Notification and exam dates vary by recruitment cycle — check the official BSSC site for current openings.",
    eligibility: "Diploma in relevant Engineering discipline. Bihar domicile typically required. Age limit varies by category.",
    exam_pattern: "Written objective-type exam covering General Studies, General Science, Math, and discipline-specific Engineering questions.",
    cutoffs: "Varies by discipline, post, and category each cycle.",
    application: "Apply via bssc.bihar.gov.in during the notified application window.",
    after_exam: "Document verification followed by posting to the allotted Bihar state engineering department.",
    faqs: "Q: Is Bihar domicile mandatory? A: Yes for most BSSC recruitments — check specific notification.",
    disclaimer: "BSSC updates notifications periodically — confirm exact details on the official website.",
  },

  "IBPS PO": {
    full_name: "Institute of Banking Personnel Selection — Probationary Officer",
    official_url: "https://www.ibps.in",
    category: "Banking & Finance",
    about: "IBPS PO recruits Probationary Officers for 11+ public sector banks (excluding SBI) through a common written exam — one of India's largest banking recruitment drives.",
    opportunities: "Probationary Officer / Management Trainee roles at public sector banks like Bank of Baroda, Canara Bank, PNB, and others, with growth into branch management roles.",
    timeline: "Notification: July/August. Prelims: October. Mains: November. Interview: Jan-Feb (following year).",
    eligibility: "Graduation in any discipline. Age 20-30, with relaxation for reserved categories.",
    exam_pattern: "Prelims: English, Quant, Reasoning (100 marks, 1 hour). Mains: Reasoning & Computer Aptitude, English, Data Analysis, GK/Banking Awareness (200 marks) + descriptive test.",
    cutoffs: "Varies by participating bank, category, and year — sectional and overall cutoffs both apply.",
    application: "Apply at ibps.in during the notified window. Fee: ₹850 (General/OBC), ₹175 (SC/ST/PwD).",
    after_exam: "Selected candidates undergo training before joining as Probationary Officer at the allotted bank.",
    faqs: "Q: Can I choose my bank? A: You list preferences; allotment depends on rank and vacancy.",
    disclaimer: "Participating banks and exact dates change yearly — confirm on ibps.in.",
  },

  "IBPS RRB": {
    full_name: "Institute of Banking Personnel Selection — Regional Rural Banks",
    official_url: "https://www.ibps.in",
    category: "Banking & Finance",
    about: "IBPS RRB recruits Office Assistants and Officers (Scale I/II/III) for Regional Rural Banks across India through a common recruitment process.",
    opportunities: "Office Assistant (Multipurpose) and Officer Scale I/II/III roles at Regional Rural Banks, serving rural and semi-urban banking needs.",
    timeline: "Notification: usually mid-year. Prelims and Mains conducted over the following months.",
    eligibility: "Graduation in any discipline (local language knowledge often preferred/required). Age 18-28 (Office Assistant), up to 40 for senior Officer Scale III.",
    exam_pattern: "Single-tier (Office Assistant) or two-tier (Officers): Reasoning, Quant, English/Hindi, GK, Computer Knowledge.",
    cutoffs: "Varies by RRB zone, post, and category.",
    application: "Apply at ibps.in during the application window.",
    after_exam: "Selected candidates are posted to a Regional Rural Bank branch in their preferred zone.",
    faqs: "Q: Is local language knowledge mandatory? A: Often yes, especially for Office Assistant posts — check the specific RRB requirement.",
    disclaimer: "RRB zones and vacancies vary by state and year — confirm exact details on ibps.in.",
  },

  "SBI PO": {
    full_name: "State Bank of India — Probationary Officer",
    official_url: "https://sbi.co.in/web/careers",
    category: "Banking & Finance",
    about: "SBI PO recruits Probationary Officers directly into India's largest public sector bank, with a clear long-term career growth path into senior management.",
    opportunities: "Starts as Assistant Manager (Scale I), with a defined promotion path: Deputy Manager → Manager → Senior Manager → Chief Manager → AGM → DGM → GM.",
    timeline: "Notification: April/May. Prelims: June/July. Mains: following month. Group Exercise & Interview: after Mains.",
    eligibility: "Graduation in any discipline. Age 21-30, with relaxation for reserved categories.",
    exam_pattern: "Prelims (1 hr): English, Quant, Reasoning. Mains (3.5 hrs): objective + descriptive (essay/letter writing). Followed by Group Exercise + Interview.",
    cutoffs: "Varies by category and year — SBI typically releases 2000-3000+ PO vacancies annually.",
    application: "Apply at sbi.co.in/web/careers. Fee: ₹750 (General/OBC), free for SC/ST/PwD.",
    after_exam: "Selected candidates undergo training before joining as Probationary Officer at an SBI branch.",
    faqs: "Q: Is there a service bond? A: Yes, selected candidates typically must serve a minimum period or pay a bond amount.",
    disclaimer: "Vacancy numbers and exact dates vary yearly — confirm on the official SBI careers page.",
  },

  "RBI Grade B": {
    full_name: "Reserve Bank of India — Grade B Officer",
    official_url: "https://opportunities.rbi.org.in",
    category: "Banking & Finance",
    about: "RBI Grade B recruits officers directly into India's central bank, regarded as one of the most prestigious banking exams due to RBI's regulatory role and excellent compensation.",
    opportunities: "Officer roles in General, DEPR (Economic Policy Research), and DSIM (Statistics) streams, working on monetary policy, banking regulation, and economic research.",
    timeline: "Notification: June/July. Phase I: September. Phase II: October/November. Interview: following months.",
    eligibility: "Graduation with minimum 60% marks (General stream); specific postgraduate qualifications for DEPR/DSIM streams. Age 21-30.",
    exam_pattern: "Phase I: objective (Reasoning, English, Quant, GA). Phase II: descriptive (Economic/Social Issues, English writing, Finance/Management). Followed by Interview.",
    cutoffs: "Highly competitive — typically among the toughest banking exam cutoffs in India.",
    application: "Apply at opportunities.rbi.org.in during the notified window.",
    after_exam: "Selected candidates undergo training before joining RBI's central or regional offices.",
    faqs: "Q: Is RBI Grade B harder than IBPS PO? A: Generally considered more competitive due to fewer vacancies and RBI's prestige.",
    disclaimer: "Stream-specific eligibility (DEPR/DSIM) differs significantly — check official notification carefully.",
  },

  SEBI: {
    full_name: "Securities and Exchange Board of India — Grade A Officer",
    official_url: "https://www.sebi.gov.in/sebiweb/careers/Careers.jsp",
    category: "Banking & Finance",
    about: "SEBI recruits Grade A (Assistant Manager) officers to regulate India's securities markets — a prestigious role in financial market regulation.",
    opportunities: "Assistant Manager roles across General, Legal, IT, Engineering, and Research streams within SEBI's regulatory departments.",
    timeline: "Notification typically mid-year; Phase I, Phase II, and Interview spread across the following months.",
    eligibility: "Graduation/Postgraduation in relevant discipline depending on stream. Age 21-30, with relaxation for reserved categories.",
    exam_pattern: "Phase I: objective test (General Awareness, English, Quant, Reasoning + stream paper). Phase II: stream-specific paper + English (descriptive). Phase III: Interview.",
    cutoffs: "Highly competitive — limited vacancies each cycle.",
    application: "Apply via sebi.gov.in/sebiweb/careers during the notification window.",
    after_exam: "Selected candidates join as Assistant Manager at a SEBI regional office.",
    faqs: "Q: Which streams are available? A: General, Legal, Information Technology, Engineering, and Research, among others.",
    disclaimer: "Stream-wise vacancies and eligibility vary by cycle — confirm exact details on the official SEBI careers page.",
  },

  NABARD: {
    full_name: "National Bank for Agriculture and Rural Development — Grade A Officer",
    official_url: "https://www.nabard.org/careers.aspx",
    category: "Banking & Finance",
    about: "NABARD recruits Grade A (Assistant Manager) officers for its development banking role supporting agriculture and rural development across India.",
    opportunities: "Assistant Manager roles across General, Rajbhasha, and specialist streams (IT, Civil Engineering, etc.) within NABARD's regional offices.",
    timeline: "Notification typically mid-year; Phase I, Phase II, and Interview conducted over the following months.",
    eligibility: "Graduation with minimum 60% marks (General stream); discipline-specific requirements for specialist streams. Age 21-30.",
    exam_pattern: "Phase I: objective test (Reasoning, English, Quant, GK, Computer, Agriculture/Rural Development). Phase II: descriptive English + stream-specific paper. Phase III: Interview.",
    cutoffs: "Competitive, with limited vacancies — varies each year.",
    application: "Apply at nabard.org/careers.aspx during the notification window.",
    after_exam: "Selected candidates join as Assistant Manager at a NABARD regional office, working on rural credit and development schemes.",
    faqs: "Q: Is agriculture background required? A: Not mandatory for General stream, but the syllabus covers agriculture/rural development topics.",
    disclaimer: "Specialist stream eligibility varies — confirm exact requirements in the official notification each cycle.",
  },

};

export const gateContent = {
  about: "GATE (Graduate Aptitude Test in Engineering) is a national-level exam jointly conducted by IISc Bangalore and seven IITs (on rotation) to test comprehensive understanding of undergraduate-level subjects in Engineering, Technology, Architecture, and Science. A valid GATE score is used for admission to M.Tech/PhD programs at IITs/NITs/IISc, and for direct recruitment to Group A posts in PSUs like ONGC, NTPC, IOCL, BHEL, and others. Many DRDO/BARC scientist recruitments also accept GATE scores.",
  syllabus: "GATE syllabus varies by paper/branch but generally includes two parts: General Aptitude (verbal & numerical reasoning — common to all papers, ~15% weightage) and the Core Subject (specific to your chosen branch, e.g. CS: Programming, Data Structures, Algorithms, OS, DBMS, Computer Networks, Theory of Computation, Compiler Design, Digital Logic, Computer Organization, Discrete Maths; ME: Engineering Mechanics, Strength of Materials, Thermodynamics, Fluid Mechanics, Manufacturing; EE: Electric Circuits, Signals & Systems, Control Systems, Power Systems, Electrical Machines). Full official syllabus PDFs are published on the GATE website (gate2026.iitr.ac.in or the relevant year's organizing institute site) under 'Syllabus' for each of the 30 papers.",
  pyq: null, // Coming soon — handled in UI
};